import os
import json
from dotenv import load_dotenv
from huggingface_hub import InferenceClient
import re


load_dotenv()

hf_token = os.getenv("HF_TOKEN")

client = InferenceClient(
    model="meta-llama/Llama-3.1-8B-Instruct:cerebras", 
    token=hf_token
)

def get_json_response(system_prompt, user_prompt):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    response = client.chat_completion(
        messages=messages,
        max_tokens=1500,
        temperature=0.2
    )

    content = response.choices[0].message.content.strip()

    json_text = extract_json(content)

    return json.loads(json_text)


def extract_json(text):
    """
    Extract the first JSON object or array by bracket matching.
    Works with nested JSON and ignores extra text.
    """
    start = None
    stack = []
    
    for i, ch in enumerate(text):
        if ch in ['{', '[']:
            if start is None:
                start = i
            stack.append(ch)

        elif ch in ['}', ']'] and stack:
            opening = stack.pop()

            # Mismatched bracket protection
            if (opening == '{' and ch != '}') or (opening == '[' and ch != ']'):
                continue

            # If stack empty -> we've closed the full JSON
            if not stack:
                return text[start:i+1]

    raise ValueError("No complete JSON found in model response")


print("Step 1: Project Description (Input)")
project_input = """
We are building a food delivery app for 10,000 users per month. 
Budget: ₹50,000 per month. 
Tech stack: Node.js backend, PostgreSQL database, object storage for images, monitoring, and basic analytics. 
Non-functional requirements: scalability, cost efficiency, uptime monitoring.
"""
print(project_input.strip())
print("-" * 50)

system_prompt_profile = """
You are a technical architect. Extract details from the project description and output strictly a valid JSON object.
Do not include any markdown formatting or explanatory text outside the JSON.
Required keys: "name", "budget_inr_per_month" (integer), "description", "tech_stack" (object), "non_functional_requirements" (list).
"""

try:
    profile_json = get_json_response(system_prompt_profile, project_input)
    
    print("\n2.10.2 Step 2: Project Profile (Generated by LLM)")
    print(json.dumps(profile_json, indent=4))

except Exception as e:
    print(f"Error in Step 2: {e}")
    profile_json = None

if profile_json:
    system_prompt_billing =system_prompt_billing = """
                You are a cloud billing generator. Based on the project profile, generate a synthetic monthly billing dataset.
                The billing MUST match these rules:

                - Output ONLY valid JSON. No explanations. No markdown. No text outside JSON.
                - JSON must be a LIST of 12–20 objects.
                - Total monthly cost must NOT exceed the project's budget.
                - Use cloud-agnostic names (Compute Instance, Object Storage, Database Instance, Monitoring, Analytics, etc.)
                - The project profile determines the scale of usage (food delivery app, 10,000 users, Node.js, PostgreSQL, image storage).

                Each billing record MUST contain:

                "month": "2025-01",
                "service": "Compute Instance | Database Instance | Object Storage | Monitoring | Analytics | etc.",
                "resource_id": "string",
                "region": "string",
                "usage_type": "string",
                "usage_quantity": number,
                "unit": "hours | GB | requests | objects | rows | etc.",
                "cost_inr": integer,
                "desc": "short description of the resource"

                Return ONLY the JSON array.
                """

    
    user_prompt_billing = f"Create a billing breakdown for this profile: {json.dumps(profile_json)}"

    try:
        billing_json = get_json_response(system_prompt_billing, user_prompt_billing)
        
        print("\n2.10.3 Step 3: Synthetic Billing (Generated by LLM)")
        print(json.dumps(billing_json, indent=4))
        
    except Exception as e:
        print(f"Error in Step 3: {e}")