import os
import json
from dotenv import load_dotenv
from huggingface_hub import InferenceClient

load_dotenv()

hf_token = os.getenv("HF_TOKEN")

client = InferenceClient(
    model="meta-llama/Llama-3.1-8B-Instruct:cerebras", 
    token=hf_token
)

def get_json_response(system_prompt, user_prompt):
    """
    Sends a prompt to the LLM and parses the JSON response.
    """
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    response = client.chat_completion(
        messages=messages, 
        max_tokens=1000, 
        temperature=0.2 
    )
    
    content = response.choices[0].message.content.strip()
    if content.startswith("```json"):
        content = content[7:]
    if content.endswith("```"):
        content = content[:-3]
        
    return json.loads(content)

print("Step 1: Project Description (Input)")
project_input = """
We are building a food delivery app for 10,000 users per month. 
Budget: ₹50,000 per month. 
Tech stack: Node.js backend, PostgreSQL database, object storage for images, monitoring, and basic analytics. 
Non-functional requirements: scalability, cost efficiency, uptime monitoring.
"""
print(project_input.strip())
print("-" * 50)

system_prompt_profile = """
You are a technical architect. Extract details from the project description and output strictly a valid JSON object.
Do not include any markdown formatting or explanatory text outside the JSON.
Required keys: "name", "budget_inr_per_month" (integer), "description", "tech_stack" (object), "non_functional_requirements" (list).
"""

try:
    profile_json = get_json_response(system_prompt_profile, project_input)
    
    print("\n2.10.2 Step 2: Project Profile (Generated by LLM)")
    print(json.dumps(profile_json, indent=4))

except Exception as e:
    print(f"Error in Step 2: {e}")
    profile_json = None

if profile_json:
    system_prompt_billing = """
    You are a cloud cost estimator. Based on the provided Project Profile JSON, create a synthetic monthly billing breakdown in INR.
    The sum of costs must be approximately equal to the budget.
    Output strictly a valid JSON List of objects.
    Each object must have keys: "service", "cost_inr" (integer), "desc".
    """
    
    user_prompt_billing = f"Create a billing breakdown for this profile: {json.dumps(profile_json)}"

    try:
        billing_json = get_json_response(system_prompt_billing, user_prompt_billing)
        
        print("\n2.10.3 Step 3: Synthetic Billing (Generated by LLM)")
        print(json.dumps(billing_json, indent=4))
        
    except Exception as e:
        print(f"Error in Step 3: {e}")